# Each route describes how an incoming URL is going to be processed by Platform.sh.
'https://www.{default}/api':
  type: upstream
  upstream: 'app:http'

'https://{default}/qrcode':
  type: redirect
  to: 'https://www.{default}/'

'https://{default}/movies':
  type: redirect
  to: 'https://www.{default}/'
